version: "3.9"

services:

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: smart-recipe-cloudflare
    command: proxy-dns
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart-recipe-backend
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Paris
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smart-recipe-frontend
    expose:
      - "80"
    restart: unless-stopped

  proxy:
    image: caddy:2
    container_name: smart-recipe-proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - cloudflare
      - backend
      - frontend
    restart: unless-stopped
